# Generated by Django 2.1 on 2020-05-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='choice',
            field=models.CharField(choices=[('#Financial', '#Financial'), ('#Political', '#Political'), ('#Religious', '#Religious'), ('#Offensive', '#Offensive'), ('#Funny', '#Funny')], max_length=20),
        ),
    ]
